// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace NarvaezEsteban_ExamenProgreso1.Migrations
{
    [DbContext(typeof(UsuarioContext))]
    partial class UsuarioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NarvaezEsteban_ExamenProgreso1.Models.Celular", b =>
                {
                    b.Property<int>("IdCelular")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCelular"));

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("año")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<int>("precio")
                        .HasColumnType("int");

                    b.HasKey("IdCelular");

                    b.ToTable("Celular");
                });

            modelBuilder.Entity("NarvaezEsteban_ExamenProgreso1.Models.Narvaez", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Altura")
                        .HasColumnType("real");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Fechanacimiento")
                        .HasColumnType("date");

                    b.Property<int>("IdCelular")
                        .HasColumnType("int");

                    b.Property<bool>("Nacionalidad")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdCelular");

                    b.ToTable("Narvaez");
                });

            modelBuilder.Entity("NarvaezEsteban_ExamenProgreso1.Models.Narvaez", b =>
                {
                    b.HasOne("NarvaezEsteban_ExamenProgreso1.Models.Celular", "Celular")
                        .WithMany()
                        .HasForeignKey("IdCelular")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Celular");
                });
#pragma warning restore 612, 618
        }
    }
}
